version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - UVICORN_WORKERS=4
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/number-input-app
    container_name: react-frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     # Step 1: Checkout the code
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     # Step 2: Set up AWS CLI
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     # Step 3: Deploy to EC2 via AWS SSM
  #     - name: Deploy to EC2 via AWS SSM
  #       run: |
  #         aws ssm send-command \
  #           --document-name "AWS-RunShellScript" \
  #           --targets "Key=instanceIds,Values=your-ec2-instance-id" \
  #           --parameters commands="cd /path/to/your/project && docker-compose pull && docker-compose up -d" \
  #           --comment "Deploying updated Docker containers to EC2"
