name: CI/CD Pipeline with Docker Hub and EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerbackend:latest ./backend

      # Step 4: Build the frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerfrontend:latest ./frontend/number-input-app

      # Step 5: Push the backend Docker image to Docker Hub
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerbackend:latest

      # Step 6: Push the frontend Docker image to Docker Hub
      - name: Push Frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerfrontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Step 3: Deploy to EC2 via AWS SSM
      - name: Deploy to EC2 via AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-0e5fdd40de475bea5" \
            --parameters commands="cd /home/ubuntu && docker compose stop && docker compose rm -f && docker compose pull && docker compose up -d" \
            --comment "Deploying updated Docker containers to EC2
