name: CI/CD Pipeline with Docker Hub and EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerbackend:latest ./backend

      # Step 4: Build the frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerfrontend:latest ./frontend/number-input-app

      # Step 5: Push the backend Docker image to Docker Hub
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerbackend:latest

      # Step 6: Push the frontend Docker image to Docker Hub
      - name: Push Frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simplewebwithdockerfrontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/assignment4.pem
          chmod 600 ~/.ssh/assignment4.pem  # Ensure the private key has the correct permissions

      - name: Start ssh-agent and add the key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/assignment4.pem

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -t ed25519 54.210.66.194 >> ~/.ssh/known_hosts  # Add the EC2 instance to known_hosts to avoid the prompt

      - name: Run deployment script on EC2
        run: |
          ssh -i ~/.ssh/assignment4.pem -T ubuntu@54.210.66.194 << 'EOF'
            cd /home/ubuntu
            docker compose stop
            docker compose rm -f
            docker compose pull
            docker compose up -d
          EOF
